# Generated by Django 5.2.3 on 2025-09-08 14:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Номер телефона должен быть в международном формате, например +996555123456', regex='^\\\\+?1?\\\\d{9,15}$')]),
        ),
    ]
