# Generated by Django 5.2.3 on 2025-07-02 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_deliveryzone_restaurant_order_actual_delivery_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Наличные'), ('card', 'Карта'), ('online', 'Онлайн'), ('elcart', 'Элкарт'), ('mbank', 'МБанк'), ('eldik', 'Элдик'), ('optima', 'Optima Bank'), ('demir', 'Demir Bank'), ('bakai', 'Bakai Bank'), ('kompanion', 'Kompanion Bank'), ('rahatpay', 'Рахат Pay'), ('kaspi', 'Kaspi'), ('applepay', 'Apple Pay'), ('googlepay', 'Google Pay')], default='cash', max_length=20),
        ),
    ]
