# Generated by Django 5.2.3 on 2025-08-16 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0007_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='partner_user',
            field=models.ForeignKey(blank=True, help_text='Пользователь, управляющий этим рестораном (партнёр-магазин)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_restaurants', to='delivery.userprofile'),
        ),
    ]
