# Generated by Django 5.2.3 on 2025-08-16 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0008_restaurant_partner_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryperson',
            name='document_back_image',
            field=models.ImageField(blank=True, help_text='Изображение обратной стороны документа', null=True, upload_to='documents/back/'),
        ),
        migrations.AddField(
            model_name='deliveryperson',
            name='document_front_image',
            field=models.ImageField(blank=True, help_text='Изображение лицевой стороны документа', null=True, upload_to='documents/front/'),
        ),
        migrations.AddField(
            model_name='deliveryperson',
            name='document_number',
            field=models.CharField(blank=True, help_text='Номер документа', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deliveryperson',
            name='document_submission_date',
            field=models.DateTimeField(auto_now_add=True, help_text='Дата подачи документов', null=True),
        ),
        migrations.AddField(
            model_name='deliveryperson',
            name='document_type',
            field=models.CharField(blank=True, help_text='Тип документа (паспорт, права и т.д.)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='deliveryperson',
            name='is_documents_verified',
            field=models.BooleanField(default=False, help_text='Статус верификации документов'),
        ),
    ]
