# Generated by Django 5.2.3 on 2025-08-16 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0010_payout'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Промокод (например, NEWYEAR2024)', max_length=50, unique=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Процентная скидка'), ('fixed_amount', 'Фиксированная сумма'), ('free_delivery', 'Бесплатная доставка')], default='fixed_amount', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Значение скидки (например, 10 для 10% или 150 для 150 ед.)', max_digits=5)),
                ('start_date', models.DateTimeField(help_text='Дата начала действия промокода')),
                ('end_date', models.DateTimeField(help_text='Дата окончания действия промокода')),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Минимальная сумма заказа для применения промокода', max_digits=10)),
                ('is_active', models.BooleanField(default=True, help_text='Активен ли промокод')),
                ('usage_limit', models.PositiveIntegerField(blank=True, help_text='Максимальное количество использований промокода', null=True)),
                ('times_used', models.PositiveIntegerField(default=0, help_text='Сколько раз промокод был использован')),
            ],
        ),
    ]
