# Generated by Django 5.2.3 on 2025-08-16 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0011_promocode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('cart', 'Корзина'), ('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтвержден'), ('preparing', 'Готовится'), ('assigned', 'Назначен курьер'), ('picked_up', 'Курьер забрал'), ('delivering', 'Доставляется'), ('delivered', 'Доставлен'), ('cancelled', 'Отменен')], default='pending', max_length=20),
        ),
    ]
