#Generated by Django 5.2.3 on 2025-09-06 18:11

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    # This migration previously contained many schema operations
    # generated from a different development branch. The current
    # repository's initial migration already reflects the desired
    # schema, so we make this migration a no-op to avoid conflicts
    # during apply. If you need to reintroduce any operations, add
    # them here explicitly.
    operations = [
        migrations.RunPython(lambda apps, schema_editor: None, reverse_code=lambda apps, schema_editor: None),
    ]
