repos:
  # Python code formatting and linting
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: debug-statements
      - id: requirements-txt-fixer

  # Black code formatter
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        language_version: python3.10
        args: [--line-length=120]

  # isort import sorting
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--profile", "black"]

  # Flake8 linting
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        additional_dependencies: [
          'flake8-bugbear',
          'flake8-comprehensions',
          'flake8-mutable',
        ]
        args: [
          '--max-line-length=120', 
          '--max-complexity=10'
        ]

  # Bandit security linter
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.8
    hooks:
      - id: bandit
        args: ['-c', 'pyproject.toml']
        additional_dependencies: ['bandit[toml]']

  # Django checks
  - repo: https://github.com/adamchainz/django-upgrade
    rev: 1.16.0
    hooks:
      - id: django-upgrade
        args: [--target-version, "5.0"]

  # Type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
      - id: mypy
        additional_dependencies: [
          'types-all',
          'django-stubs',
          'djangorestframework-stubs'
        ]
        args: [
          '--ignore-missing-imports',
          '--follow-imports=silent',
          '--show-column-numbers'
        ]

# Global configuration
default_language_version:
  python: python3.10

# Optional: Minimum pre-commit version
minimum_pre_commit_version: '2.20.0'
